name: run-tests

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.2', '8.1', '8.0', '7.4']
        laravel: ['11.*', '10.*', '9.*', '8.*']
        dependency-version: ['prefer-lowest', 'prefer-stable']
        exclude:
          - laravel: '11.*'
            php: '8.1'
          - laravel: '11.*'
            php: '8.0'
          - laravel: '11.*'
            php: '7.4'
          - laravel: '10.*'
            php: '8.0'
          - laravel: '10.*'
            php: '7.4'
          - laravel: '9.*'
            php: '7.4'

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - run: vendor/bin/phpunit
